[package]
name = "flow-cli"
version = "0.1.0"
authors = ["ko1N <ko1N1337@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.*"
pretty_env_logger = "0.*"
flow-core = { path = "../flow-core" }
flow-qemu = { path = "../flow-qemu" }
flow-win32 = { path = "../flow-win32" }
address = { path = "../flow-core/address" }
mem = { path = "../flow-core/mem" }
goblin = { path = "../../goblin-mapped" }
