pdb_file_name = 'ntkrnlmp.pdb'
pdb_guid = 'BBED7C2955FBE4522AAA23F4B8677AD91'
nt_major_version = 10
nt_minor_version = 0
nt_build_number = 19041
arch = 'X64'

[offsets]
list_blink = 8
eproc_link = 1096
phys_mem_block = 13612224
kproc_dtb = 40
eproc_pid = 1088
eproc_name = 1448
eproc_peb = 1360
eproc_section_base = 1312
eproc_exit_status = 2004
eproc_thread_list = 1504
eproc_wow64 = 1408
eproc_vad_root = 2008
kthread_teb = 240
ethread_list_entry = 1256
teb_peb = 96
teb_peb_x86 = 48
balanced_node_left = 0
balanced_node_right = 8
mm_vad_vad_node = 0
mm_vad_starting_vpn = 24
mm_vad_ending_vpn = 28
mm_vad_starting_vpn_high = 32
mm_vad_ending_vpn_high = 33
mm_vad_u = 48
