pdb_file_name = 'ntkrnlmp.pdb'
pdb_guid = '1C9875F76C8F0FBF3EB9A9D7C1C274061'
nt_major_version = 10
nt_minor_version = 0
nt_build_number = 19041
arch = 'X64'

[offsets]
list_blink = 8
eproc_link = 1096
kproc_dtb = 40
eproc_pid = 1088
eproc_name = 1448
eproc_peb = 1360
eproc_section_base = 1312
eproc_exit_status = 2004
eproc_thread_list = 1504
eproc_wow64 = 1408
kthread_teb = 240
ethread_list_entry = 1256
teb_peb = 96
teb_peb_x86 = 48
