pdb_guid = '82DCF67A38274C9CA99B60B421D2786D2'
nt_major_version = 5
nt_minor_version = 2
nt_build_number = 3790
arch = 'X64'

[offsets]
list_blink = 8
eproc_link = 224
kproc_dtb = 40
eproc_pid = 216
eproc_name = 616
eproc_peb = 704
eproc_section_base = 0x128
eproc_exit_status = 0x024C
eproc_thread_list = 656
eproc_wow64 = 680
kthread_teb = 176
ethread_list_entry = 976
teb_peb = 96
teb_peb_x86 = 48
