pdb_file_name = 'ntkrpamp.pdb'
pdb_guid = '684DA42A30CC450F81C535B4D18944B12'
nt_major_version = 6
nt_minor_version = 1
nt_build_number = 7601
arch = 'X86'

[offsets]
list_blink = 4
eproc_link = 184
kproc_dtb = 24
eproc_pid = 180
eproc_name = 364
eproc_peb = 424
eproc_section_base = 300
eproc_exit_status = 628
eproc_thread_list = 392
eproc_wow64 = 0
kthread_teb = 136
ethread_list_entry = 616
teb_peb = 48
teb_peb_x86 = 48
